import { useEffect, useState } from "react"
import { CheckCircle2, Loader2, Save } from "lucide-react"
import AppShell from "../components/AppShell"
import api, { getApiError } from "../lib/api"

function Settings() {
  const [form, setForm] = useState({ name: "", phone: "", college: "", degree: "", skills: "", graduation_year: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("")
  useEffect(() => { api.get("/profile").then(({ data }) => setForm({ name: data.name || "", phone: data.phone || "", college: data.college || "", degree: data.degree || "", skills: data.skills || "", graduation_year: data.graduation_year || "" })).catch((requestError) => setError(getApiError(requestError))).finally(() => setLoading(false)) }, [])
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }))
  const save = async (event) => { event.preventDefault(); try { setSaving(true); setError(""); setMessage(""); const payload = { ...form, graduation_year: form.graduation_year ? Number(form.graduation_year) : null }; const response = await api.put("/profile", payload); setForm((current) => ({ ...current, ...response.data.profile })); setMessage("Profile saved successfully.") } catch (requestError) { setError(getApiError(requestError, "Unable to save your profile.")) } finally { setSaving(false) } }
  const fields = [{ name: "name", label: "Full name", placeholder: "Your full name" }, { name: "phone", label: "Phone number", placeholder: "10 digit phone number" }, { name: "college", label: "College or university", placeholder: "Your institution" }, { name: "degree", label: "Degree", placeholder: "B.Tech Computer Science" }, { name: "graduation_year", label: "Graduation year", placeholder: "2026", type: "number" }]
  return <AppShell eyebrow="Your profile" title="Settings" description="Keep your career profile current so the recommendations stay relevant.">
    {loading ? <div className="flex justify-center rounded-[26px] bg-white/60 p-16"><Loader2 className="h-7 w-7 animate-spin text-indigo-500" /></div> : <form onSubmit={save} className="max-w-3xl rounded-[30px] bg-white/60 p-6 shadow-sm sm:p-8"><div className="grid gap-5 sm:grid-cols-2">{fields.map((field) => <label key={field.name} className="text-sm font-semibold text-slate-700">{field.label}<input required={field.name === "name"} type={field.type || "text"} name={field.name} value={form[field.name]} onChange={update} placeholder={field.placeholder} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label>)}</div><label className="mt-5 block text-sm font-semibold text-slate-700">Skills<span className="mt-1 block text-xs font-normal text-slate-400">Separate skills with commas</span><textarea name="skills" value={form.skills} onChange={update} rows="4" placeholder="React, Python, SQL" className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-white px-4 py-3 font-normal outline-none focus:border-indigo-500 focus:ring-4 focus:ring-indigo-100" /></label>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}{message && <p className="mt-4 flex items-center gap-2 text-sm text-emerald-600"><CheckCircle2 className="h-4 w-4" />{message}</p>}<button disabled={saving} className="mt-6 flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white transition hover:bg-indigo-700 disabled:opacity-50">{saving ? <Loader2 className="h-5 w-5 animate-spin" /> : <Save className="h-5 w-5" />}Save profile</button></form>}
  </AppShell>
}
export default Settings
